### PR TITLE
A few updates to get the templates working with the current fxhash API (project SDK)

### PR DESCRIPTION
**Pull request by nclslbrn**
Just tested on sandbox https://www.fxhash.xyz/sandbox but not in production (testnet/mainnet).

### CODE REVIEW

**Comment by postspectacular** [comment]
@nclslbrn - oh my gosh this is freaky timing - i've literallly just started working on updating this & other project templates... thank you very much! LGTM! 👍

**Comment by nclslbrn** [comment]
I just found out that there was something new in thi.ng/umbrella/random-fxhash, so I saw an opportunity to help out, but in the end, I'm just helping you help me. These packages help me a lot.

**Comment by audionerd** [comment]
Thanks for this! 

I made a slight modification in my project to use the 
[FxHashApi](https://github.com/fxhash/fxhash-package/blob/49f8967/packages/project-sdk/src/types.ts#L10-L31) type instead of defining an `fxProjectSDK`. That does add an extra dependency to `@fxhash/project-sdk` however.

**Comment by nclslbrn** [comment]
Interesting, this seems to bring better/complete FxHashApi integration, could you send a pull request? 
I think @postspectacular might be interested in this development, in fact so am I, but not as a maintainer, but as a user of this template.

**Comment by postspectacular** [comment]
@audionerd @nclslbrn Yeah, I'd appreciate a PR, especially since that only seems to be a type-only import of their interface(s)... thank you!

**Pull request merged**
