### PR TITLE
Upgrade to latest fxhash project SDK

### PR DESCRIPTION
**Pull request by jffaust**
- Replace the old fxhash snippet in `index.html` by a reference to the new SDK as a standalone file. The new file is under the `public` folder so that `vite` doesn't do any transform on it (it needs to stay identical so fxhash can validate it when trying to upload a generative token) but still include it in the dist.
- Upgrade version of `@thi.ng/random-fxhash` to `0.3.18` that supports the new SDK
- Update `vite build` command to omit the extra single quotes
- Add new `fxhash.js` to the `bundle` command so it gets zipped (couldn't test that one as I'm on Windows)
- Update documentation to reference which version is used

### CODE REVIEW

**Comment by jffaust** [comment]
I'm able to upload the template successfully: 
image

**Comment by jffaust** [comment]
@postspectacular Could you validate the changes on your side? I think there might be some different behavior because I'm on Windows and I think you're not. 

Not sure if that's why but I had to change the `vite build` command to remove the single quotes because vite would generate paths like these in the dist: `<script src="/'./'/fxhash.js">` and `<script type="module" crossorigin src="/'./'/assets/index-210b0b79.js">`

**Comment by postspectacular** [comment]
Thanks, @jffaust - I've checked it on my Mac and also the minting UI (as you did) - it all seems to work fine... however, the FX sandbox doesn't work at all, but looks like it's an issue on their end, since most of those errors are already thrown before the ZIP upload. But the sandbox also doesn't seem to find the new SDK snippet (last error). Always had issues with that sandbox in the past, so let's ignore...

Screenshot 2023-11-05 at 10 50 06

**Comment by jffaust** [comment]
Yes actually I asked about the sandbox issues on the Discord server and they told me it was in a bad state.

**Pull request merged**
